import { plannerStateSchema, type PlannerState } from '@/features/planner/domain/planner.types'

export const seedPlannerState: PlannerState = plannerStateSchema.parse({
  teachers: [
    { id: 'teacher-camilla', name: 'Camilla Nilsen', firstName: 'Camilla' },
    { id: 'teacher-jesper', name: 'Jesper Dahl', firstName: 'Jesper' },
    { id: 'teacher-liv', name: 'Liv Haugen', firstName: 'Liv' },
    { id: 'teacher-sami', name: 'Sami Ali', firstName: 'Sami' },
    { id: 'teacher-nora', name: 'Nora Berg', firstName: 'Nora' },
    { id: 'teacher-henrik', name: 'Henrik Lunde', firstName: 'Henrik' },
  ],
  substitutes: [
    {
      id: 'sub-ida',
      name: 'Ida Solheim',
      firstName: 'Ida',
      initials: 'IS',
      avatarColor: '#E9B8A6',
    },
    {
      id: 'sub-maja',
      name: 'Maja Foss',
      firstName: 'Maja',
      initials: 'MF',
      avatarColor: '#F2D39B',
    },
    {
      id: 'sub-emil',
      name: 'Emil Lie',
      firstName: 'Emil',
      initials: 'EL',
      avatarColor: '#D9E3C3',
    },
    {
      id: 'sub-sigrid',
      name: 'Sigrid Viken',
      firstName: 'Sigrid',
      initials: 'SV',
      avatarColor: '#D7C4E8',
    },
    {
      id: 'sub-tariq',
      name: 'Tariq Noor',
      firstName: 'Tariq',
      initials: 'TN',
      avatarColor: '#BFD5E5',
    },
    {
      id: 'sub-lina',
      name: 'Lina Holm',
      firstName: 'Lina',
      initials: 'LH',
      avatarColor: '#E8CFB8',
    },
    {
      id: 'sub-oskar',
      name: 'Oskar Aas',
      firstName: 'Oskar',
      initials: 'OA',
      avatarColor: '#D7D7D7',
    },
  ],
  timeBlocks: [
    { id: 'block-1', label: '08:30-09:30', start: '08:30', end: '09:30', order: 0 },
    { id: 'block-2', label: '09:30-10:30', start: '09:30', end: '10:30', order: 1 },
    { id: 'block-3', label: '10:30-11:30', start: '10:30', end: '11:30', order: 2 },
    { id: 'block-4', label: '11:30-12:30', start: '11:30', end: '12:30', order: 3 },
    { id: 'block-5', label: '12:30-13:30', start: '12:30', end: '13:30', order: 4 },
    { id: 'block-6', label: '13:30-14:30', start: '13:30', end: '14:30', order: 5 },
  ],
  rows: [
    { id: 'row-1', order: 0, rowResponsibleId: null },
    { id: 'row-2', order: 1, rowResponsibleId: 'sub-ida' },
    { id: 'row-3', order: 2, rowResponsibleId: null },
    { id: 'row-4', order: 3, rowResponsibleId: null },
    { id: 'row-5', order: 4, rowResponsibleId: 'sub-sigrid' },
  ],
  needCards: [
    {
      id: 'need-1',
      title: '6A Matematikk',
      sourceTeacherId: 'teacher-camilla',
      rowId: 'row-1',
      timeBlockId: 'block-1',
      explicitAssigneeId: null,
      color: '#F6D29A',
    },
    {
      id: 'need-2',
      title: '6A Norsk',
      sourceTeacherId: 'teacher-camilla',
      rowId: 'row-1',
      timeBlockId: 'block-2',
      explicitAssigneeId: null,
      color: '#F0C79F',
    },
    {
      id: 'need-3',
      title: '6A Naturfag',
      sourceTeacherId: 'teacher-camilla',
      rowId: 'row-1',
      timeBlockId: 'block-4',
      explicitAssigneeId: null,
      color: '#E6D2AF',
    },
    {
      id: 'need-4',
      title: '8B Engelsk',
      sourceTeacherId: 'teacher-sami',
      rowId: 'row-2',
      timeBlockId: 'block-1',
      explicitAssigneeId: null,
      color: '#D8E5C7',
    },
    {
      id: 'need-5',
      title: '8B Musikk',
      sourceTeacherId: 'teacher-sami',
      rowId: 'row-2',
      timeBlockId: 'block-5',
      explicitAssigneeId: 'sub-maja',
      color: '#D5E2F0',
    },
    {
      id: 'need-6',
      title: '7C Matematikk',
      sourceTeacherId: 'teacher-jesper',
      rowId: 'row-3',
      timeBlockId: 'block-2',
      explicitAssigneeId: null,
      color: '#F2D8AE',
    },
    {
      id: 'need-7',
      title: '5A Kunst',
      sourceTeacherId: 'teacher-liv',
      rowId: 'row-3',
      timeBlockId: 'block-3',
      explicitAssigneeId: null,
      color: '#E5CAB6',
    },
    {
      id: 'need-8',
      title: '9A Naturfag',
      sourceTeacherId: 'teacher-nora',
      rowId: 'row-4',
      timeBlockId: 'block-1',
      explicitAssigneeId: null,
      color: '#D7E5D7',
    },
    {
      id: 'need-9',
      title: '9A Historie',
      sourceTeacherId: 'teacher-jesper',
      rowId: 'row-4',
      timeBlockId: 'block-4',
      explicitAssigneeId: null,
      color: '#EDD2BA',
    },
    {
      id: 'need-10',
      title: '9A Norsk',
      sourceTeacherId: 'teacher-camilla',
      rowId: 'row-4',
      timeBlockId: 'block-6',
      explicitAssigneeId: null,
      color: '#EAD9B8',
    },
    {
      id: 'need-11',
      title: '4B Lesing',
      sourceTeacherId: 'teacher-liv',
      rowId: 'row-5',
      timeBlockId: 'block-3',
      explicitAssigneeId: null,
      color: '#F2D6C9',
    },
    {
      id: 'need-12',
      title: '4B Gym',
      sourceTeacherId: 'teacher-henrik',
      rowId: 'row-5',
      timeBlockId: 'block-5',
      explicitAssigneeId: 'sub-tariq',
      color: '#D4E4D9',
    },
  ],
})
