export const PLANNER_SIDE_PANEL_WIDTH_PX = 272
export const PLANNER_ROW_HEADER_WIDTH_PX = 240
export const PLANNER_TIME_BLOCK_MIN_WIDTH_PX = 144
export const PLANNER_ROW_HEIGHT_PX = 108
export const PLANNER_GRID_HEADER_HEIGHT_PX = 72
